const DEFAULTS = { title: 'KSUCflow', institution: 'KENYA SCIENCE UNIVERSITY COLLEGE', primary: '#376fd5' };
const STARTER_USERS = [{id:1,name:'Newton Mwangi',email:'newton.mwangi@ksuc.ac.ke',department:'Registry',role:'Administrator',active:true,password:'ChangeMe123!'},{id:2,name:'James Kariuki',email:'james.kariuki@ksuc.ac.ke',department:'Finance',role:'Department Head',active:true,password:'ChangeMe123!'},{id:3,name:'Sarah Mwangi',email:'sarah.mwangi@ksuc.ac.ke',department:'Human Resources',role:'Staff',active:true,password:'ChangeMe123!'}];
const byId = id => document.getElementById(id);
const encode = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function users(){return JSON.parse(localStorage.getItem('routeflowUsers')||'null')||STARTER_USERS} function saveUsers(list){localStorage.setItem('routeflowUsers',JSON.stringify(list))} function settings(){const s=JSON.parse(localStorage.getItem('routeflowAdminSettings')||'null')||DEFAULTS;if(s.title==='RouteFlow'){s.title=DEFAULTS.title;localStorage.setItem('routeflowAdminSettings',JSON.stringify(s))}return s}
function render(){const list=users();byId('totalUsers').textContent=list.length;byId('activeUsers').textContent=list.filter(u=>u.active).length;byId('adminUsers').textContent=list.filter(u=>u.role==='Administrator').length;byId('documentTotal').textContent=JSON.parse(localStorage.getItem('ksucDocuments')||'[]').length||'—';byId('userRows').innerHTML=list.map(u=>`<tr><td><strong>${encode(u.name)}</strong><span class="email">${encode(u.email)}</span></td><td>${encode(u.department)}</td><td><span class="pill ${u.role==='Administrator'?'admin':''}">${encode(u.role)}</span></td><td><span class="status ${u.active?'active':''}">${u.active?'Active':'Disabled'}</span></td><td><div class="actions"><button data-action="reset" data-id="${u.id}">Reset password</button><button data-action="toggle" data-id="${u.id}">${u.active?'Disable':'Enable'}</button><button data-action="delete" data-id="${u.id}">Remove</button></div></td></tr>`).join('')}
function loadSettings(){const s=settings();byId('appName').value=s.title;byId('institution').value=s.institution;byId('primaryColor').value=s.primary;byId('brandName').textContent=s.title;byId('mark').textContent=s.title.charAt(0).toUpperCase();document.documentElement.style.setProperty('--blue',s.primary)}
byId('addUser').onclick=()=>{byId('userForm').reset();byId('userDialog').showModal()};byId('userForm').onsubmit=e=>{e.preventDefault();const list=users();list.push({id:Date.now(),name:byId('name').value.trim(),email:byId('email').value.trim(),department:byId('department').value,role:byId('role').value,active:true,password:byId('password').value});saveUsers(list);byId('userDialog').close();render()};byId('userRows').onclick=e=>{const b=e.target.closest('button');if(!b)return;const list=users(),u=list.find(x=>x.id===Number(b.dataset.id));if(!u)return;if(b.dataset.action==='toggle'){u.active=!u.active;saveUsers(list);render()}else if(b.dataset.action==='reset'){const p=prompt(`New temporary password for ${u.name}:`);if(p&&p.length>=8){u.password=p;saveUsers(list);alert('Password reset. Share the temporary password securely.')}else if(p)alert('Password must be at least 8 characters.')}else if(b.dataset.action==='delete'){if(confirm(`Remove ${u.name}'s account?`)){saveUsers(list.filter(x=>x.id!==u.id));render()}}};byId('saveSettings').onclick=()=>{const s={...settings(),title:byId('appName').value.trim()||DEFAULTS.title,institution:byId('institution').value.trim()||DEFAULTS.institution,primary:byId('primaryColor').value};localStorage.setItem('routeflowAdminSettings',JSON.stringify(s));loadSettings();alert('Portal settings saved.')};byId('resetSettings').onclick=()=>{localStorage.removeItem('routeflowAdminSettings');loadSettings();alert('Default portal settings restored.')};loadSettings();render();
byId('signOut').onclick=()=>{localStorage.removeItem('ksucSession');location.href='login.html'};
