const DEFAULT_USERS = [
  {id:1,name:'Newton Mwangi',email:'newton.mwangi@ksuc.ac.ke',department:'Registry',role:'Administrator',active:true,password:'ChangeMe123!'},
  {id:2,name:'James Kariuki',email:'james.kariuki@ksuc.ac.ke',department:'Finance',role:'Department Head',active:true,password:'ChangeMe123!'},
  {id:3,name:'Sarah Mwangi',email:'sarah.mwangi@ksuc.ac.ke',department:'Human Resources',role:'Staff',active:true,password:'ChangeMe123!'},
  {id:4,name:'Brian Otieno',email:'brian.otieno@ksuc.ac.ke',department:'Academic Affairs',role:'Staff',active:false,password:'ChangeMe123!'}
];
function users() { const saved = JSON.parse(localStorage.getItem('routeflowUsers') || 'null'); if (saved) return saved; localStorage.setItem('routeflowUsers', JSON.stringify(DEFAULT_USERS)); return DEFAULT_USERS; }
document.querySelector('#loginForm').addEventListener('submit', event => { event.preventDefault(); const email = document.querySelector('#email').value.trim().toLowerCase(); const password = document.querySelector('#password').value; const user = users().find(item => item.email.toLowerCase() === email && item.password === password); const error = document.querySelector('#error'); if (!user) { error.textContent = 'The email address or password is incorrect.'; return; } if (!user.active) { error.textContent = 'This account has been disabled. Contact an administrator.'; return; } localStorage.setItem('ksucSession', JSON.stringify({ id:user.id, name:user.name, role:user.role, department:user.department })); location.href = user.role === 'Administrator' ? 'admin.html' : 'index.html'; });
document.querySelector('#showPassword').addEventListener('click', event => { const field = document.querySelector('#password'); field.type = field.type === 'password' ? 'text' : 'password'; event.target.textContent = field.type === 'password' ? 'Show' : 'Hide'; });
document.querySelectorAll('[data-email]').forEach(button => button.addEventListener('click', () => { document.querySelector('#email').value = button.dataset.email; document.querySelector('#password').value = 'ChangeMe123!'; document.querySelector('#error').textContent = ''; }));
